=== Any-VM/AnyGPT/apps/api/providers.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
      "type": "object",
      "required": ["id", "apiKey", "provider_url", "models", "errors"],
      "properties": {
        "id": { "type": "string" },
        "apiKey": { "type": ["string", "null"] },
        "provider_url": { "type": "string" },
        "models": {
          "type": "object",
          "additionalProperties": {
            "type": "object",
            "properties": {
              "response_time": { "type": ["number", "null"] }
            }
          }
        },
        "avg_response_time": { "type": ["number", "null"] },
        "avg_provider_latency": { "type": ["number", "null"] },
        "errors": { "type": "number" },
        "provider_score": { "type": ["number", "null"] }
      }
    }
  }

=== Any-VM/AnyGPT/apps/api/providers.json
[
  {
    "id": "openai-t5",
    "apiKey": "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",
    "provider_url": "https://api.openai.com/v1/chat/completions",
    "models": {
      "gpt-4-turbo": {
        "response_time": null
      },
      "gpt-4-turbo-2024-04-09": {
        "response_time": null
      },
      "tts-1-1106": {
        "response_time": null
      },
      "o1-preview": {
        "response_time": null
      },
      "o1-preview-2024-09-12": {
        "response_time": null
      },
      "dall-e-2": {
        "response_time": null
      },
      "whisper-1": {
        "response_time": null
      },
      "gpt-3.5-turbo-instruct": {
        "response_time": null
      },
      "gpt-4o-mini": {
        "response_time": null
      },
      "gpt-4o": {
        "response_time": null
      },
      "tts-1-hd-1106": {
        "response_time": null
      },
      "gpt-3.5-turbo": {
        "response_time": null
      },
      "gpt-3.5-turbo-0125": {
        "response_time": null
      },
      "gpt-4-1106-vision-preview": {
        "response_time": null
      },
      "babbage-002": {
        "response_time": null
      },
      "gpt-4o-2024-05-13": {
        "response_time": null
      },
      "davinci-002": {
        "response_time": null
      },
      "gpt-4o-2024-08-06": {
        "response_time": null
      },
      "dall-e-3": {
        "response_time": null
      },
      "gpt-4o-realtime-preview": {
        "response_time": null
      },
      "gpt-4o-realtime-preview-2024-10-01": {
        "response_time": null
      },
      "gpt-3.5-turbo-0301": {
        "response_time": null
      },
      "tts-1-hd": {
        "response_time": null
      },
      "o1-mini-2024-09-12": {
        "response_time": null
      },
      "tts-1": {
        "response_time": null
      },
      "chatgpt-4o-latest": {
        "response_time": null
      },
      "o1-mini": {
        "response_time": null
      },
      "gpt-4-1106-preview": {
        "response_time": null
      },
      "text-embedding-ada-002": {
        "response_time": null
      },
      "gpt-3.5-turbo-16k": {
        "response_time": null
      },
      "gpt-4o-mini-2024-07-18": {
        "response_time": null
      },
      "text-embedding-3-small": {
        "response_time": null
      },
      "text-embedding-3-large": {
        "response_time": null
      },
      "gpt-4-vision-preview": {
        "response_time": null
      },
      "gpt-3.5-turbo-16k-0613": {
        "response_time": null
      },
      "gpt-3.5-turbo-1106": {
        "response_time": null
      },
      "gpt-4o-audio-preview": {
        "response_time": null
      },
      "gpt-3.5-turbo-0613": {
        "response_time": null
      },
      "gpt-4o-audio-preview-2024-10-01": {
        "response_time": null
      },
      "gpt-4-0613": {
        "response_time": null
      },
      "gpt-4-turbo-preview": {
        "response_time": null
      },
      "gpt-4-0125-preview": {
        "response_time": null
      },
      "gpt-4": {
        "response_time": null
      },
      "gpt-3.5-turbo-instruct-0914": {
        "response_time": null
      },
      "davinci:ft-pinkerton-2023-05-08-20-00-22": {
        "response_time": null
      },
      "davinci:ft-pinkerton-2023-05-08-14-20-04": {
        "response_time": null
      },
      "curie:ft-pinkerton-2023-05-08-20-31-02": {
        "response_time": null
      },
      "davinci:ft-pinkerton-2023-05-08-14-47-50": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-2:A3Kmhr1Y:ckpt-step-77": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-2:A3KmhPhc:ckpt-step-88": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-3:A3Ldc9hb:ckpt-step-77": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-3:A3LddXZg:ckpt-step-88": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-3:A3LddAou": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-4:A3M0Qc64": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-4:A3M0QC9T:ckpt-step-72": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-4:A3M0Qo1C:ckpt-step-84": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-knowledge-test:A1YrAaLM:ckpt-step-60": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-knowledge-test:A1YrAo8y:ckpt-step-80": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-knowledge-test:A1YrBloo": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-1:A1ZQiSCz:ckpt-step-60": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-1:A1ZQiTt5:ckpt-step-75": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-1:A1ZQiozx": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-3:A2yCGomE:ckpt-step-80": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-3:A2yCGj7q:ckpt-step-90": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-3:A2yCH6Pm": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-2:A1aN9uDs:ckpt-step-72": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-2:A1aN9Qg9:ckpt-step-84": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-2:A1aN9vcQ": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk:A30VZ6QB:ckpt-step-90": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk:A30VZ9sY:ckpt-step-80": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk:A30VZu1V": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-4o-qa-1:A4R7IHtW:ckpt-step-60": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-1:A325X3pU:ckpt-step-80": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-1:A325Xw1c:ckpt-step-90": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-1:A325Yick": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-k-test-4-gk-2:A3KmiIqb": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-4o-qa-1:A4R7Iy7U:ckpt-step-80": {
        "response_time": null
      },
      "ft:gpt-4o-2024-08-06:pinkerton:pinkerton-4o-qa-1:A4R7IqlS": {
        "response_time": null
      }
    },
    "avg_response_time": null,
    "avg_provider_latency": null,
    "errors": 0,
    "provider_score": null
  }
]
